import {
  type CaptionStyle,
  type CaptionAnimation,
  CaptionPosition,
  defaultCaptionStyle,
} from '@clipper/shared';
import { writeFileSync } from 'node:fs';

export interface CaptionSegment {
  start: number;
  end: number;
  text: string;
}

export interface AssGenerationParams {
  segments: CaptionSegment[];
  style: CaptionStyle;
  videoWidth?: number;
  videoHeight?: number;
}

function hexToAssColor(hex: string): string {
  const clean = hex.replace('#', '');
  const r = clean.slice(0, 2);
  const g = clean.slice(2, 4);
  const b = clean.slice(4, 6);
  if (clean.length === 8) {
    const a = clean.slice(6, 8);
    return `&H${a}${b}${g}${r}`;
  }
  return `&H00${b}${g}${r}`;
}

function alignmentForPosition(position: string): number {
  switch (position) {
    case CaptionPosition.TOP: return 8;
    case CaptionPosition.MIDDLE: return 5;
    case CaptionPosition.BOTTOM: return 2;
    default: return 2;
  }
}

function marginVForPosition(position: string): number {
  switch (position) {
    case CaptionPosition.TOP: return 60;
    case CaptionPosition.MIDDLE: return 0;
    case CaptionPosition.BOTTOM: return 60;
    default: return 60;
  }
}

function formatAssTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);
  return `${String(h).padStart(1, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

const FADE_TRANSITION = 150;

function buildAnimationTags(
  anim: CaptionAnimation,
  durationMs: number,
  pos: string,
  x: number,
  y: number,
  videoW: number,
  videoH: number,
): string {
  switch (anim) {
    case 'fade':
      return `{\\fad(${FADE_TRANSITION},${FADE_TRANSITION})}`;

    case 'bounce': {
      const startY = y + 40;
      const settleMs = Math.min(durationMs * 0.15, 300);
      return `{\\move(${x},${startY},${x},${y},0,${Math.round(settleMs)})}`;
    }

    case 'slide_up': {
      const startY = videoH + 60;
      return `{\\move(${x},${startY},${x},${y},0,${Math.round(durationMs * 0.15)})}`;
    }

    case 'slide_left': {
      const startX = videoW + 60;
      return `{\\move(${startX},${y},${x},${y},0,${Math.round(durationMs * 0.15)})}`;
    }

    case 'typewriter': {
      const fadeMs = Math.min(durationMs, 500);
      return `{\\fad(${Math.round(fadeMs * 0.3)},${FADE_TRANSITION})}`;
    }

    case 'scale': {
      return `{\\fscx(0)\\fscy(0)\\t(0,${Math.round(durationMs * 0.2)},\\fscx(100)\\fscy(100))}`;
    }

    case 'highlight': {
      return `{\\fad(${FADE_TRANSITION},${FADE_TRANSITION})}`;
    }

    case 'none':
    default:
      return '';
  }
}

export function generateAssContent(params: AssGenerationParams): string {
  const style = { ...defaultCaptionStyle, ...params.style };
  const w = params.videoWidth ?? 1920;
  const h = params.videoHeight ?? 1080;

  const fontColorAss = hexToAssColor(style.fontColor);
  const outlineColorAss = hexToAssColor(style.outlineColor ?? '#000000');
  const bgColorAss = hexToAssColor(style.backgroundColor);
  const alignment = alignmentForPosition(style.position);
  const marginV = marginVForPosition(style.position);

  const lines: string[] = [
    '[Script Info]',
    '; ASS caption file generated by video-clipper-generator',
    'ScriptType: v4.00+',
    `PlayResX: ${w}`,
    `PlayResY: ${h}`,
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Caption,${style.fontFamily},${style.fontSize},${fontColorAss},${fontColorAss},${outlineColorAss},${bgColorAss},0,0,0,0,100,100,0,0,1,${style.outlineWidth ?? 2},1,${alignment},20,20,${marginV},1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  for (const seg of params.segments) {
    const startFormatted = formatAssTime(seg.start);
    const endFormatted = formatAssTime(seg.end);
    const durationMs = (seg.end - seg.start) * 1000;

    const x = Math.round(w / 2);
    const y = Math.round(h / 2);

    const animTags = buildAnimationTags(style.animation, durationMs, style.position, x, y, w, h);
    const text = seg.text.replace(/\{/g, '\\{').replace(/\}/g, '\\}');

    lines.push(`Dialogue: 0,${startFormatted},${endFormatted},Caption,,0,0,0,,${animTags}${text}`);
  }

  return lines.join('\n');
}

export function writeAssFile(
  segments: CaptionSegment[],
  style: CaptionStyle,
  filePath: string,
  videoWidth?: number,
  videoHeight?: number,
): void {
  const content = generateAssContent({ segments, style, videoWidth, videoHeight });
  writeFileSync(filePath, content, 'utf-8');
}
